### ISSUE TITLE
release 3.0.3

### ISSUE THREAD

**Issue by lynxis** [projecthamster/hamster#686]
The last release (3.0.2) is missing https://github.com/projecthamster/hamster/commit/b3dc385c25c33ea5fac697e7e43cc2233234a64d It would be great to do the 3.0.3 release with this fix so distributions can pick it up.

**Comment by GeraldJansen** [comment]
Under PR #656 the NEWS.md file shows that this is already included in the upcoming 3.0.3. I don't know what we can do to encourage @matthijskooijman to proceed with the release (beg, pray, cheer, ...). Only #663 was pending but it seems ready to go.

**Comment by matthijskooijman** [comment]
> I don't know what we can do to encourage @matthijskooijman to proceed with the release 

I'm not sure if I'm the only one who can do that, but doing the release is on my mind, I just haven't found the time yet (I'm buried in deadlines atm, which should be better in a week or two, but I'm not yet sure in what order my backlog will be processing once it does...). In any case, I haven't forgotten :-)

**Comment by lynxis** [comment]
I friendly reminder and ping for the next release.

**Comment by lynxis** [comment]
I friendly reminder and ping for the next release. @matthijskooijman

**Comment by rabin-io** [comment]
Can you please tag an release 3.0.3 ?

**Comment by ederag** [comment]
A [breaking](https://github.com/projecthamster/hamster/pull/663#issuecomment-751461264) change such as #663 should not delay patch releases.

**Comment by steviehs** [comment]
I really would like to support a new release, meanwhile I had to manually apply https://github.com/projecthamster/hamster/commit/b3dc385c25c33ea5fac697e7e43cc2233234a64d as this was an annoying one :-)

**Comment by petrovo-as** [comment]
Does anyone else maintain and develop this project? I use the program every day. Thanks for the reply.

**Comment by GeraldJansen** [comment]
@aquaherd actually made the last merge, yay :-)
Any progress is much appreciated!

**Comment by petrovo-as** [comment]
Thank you for the quick reply. I just saw that no version was released in the last year. I've been looking for a time tracker for a long time and Hamster is amazing and simple. So I will send one more small problem that bothers me. :-)

**Comment by DirkHoffmann** [comment]
I never committed to doing release stuff (and previous validation, testing etc.). But if it helps, why not learn something new on github?
I may need some guidance though, @matthijskooijman. 
(@GeraldJansen, I thought you had permissions to tag/release also. Am I wrong?)

I see there is a branch [release-3.0.3](https://github.com/projecthamster/hamster/tree/release-3.0.3), which diverged (2 commits ahead of master, 5 commits behind right now, but "only" release notes). Wouldn't it be appropriate to merge that first into master, @matthijskooijman?

**Comment by matthijskooijman** [comment]
@DirkHoffmann Cool! If you're going to push this forward, hopefully that will motivate me to invest a bit of time in this as well.

> I see there is a branch [release-3.0.3](https://github.com/projecthamster/hamster/tree/release-3.0.3), which diverged (2 commits ahead of master, 5 commits behind right now, but "only" release notes). Wouldn't it be appropriate to merge that first into master, @matthijskooijman?

I would think it is better to just rebase that branch, maybe squash the commits in it together as well (and update it to include whatever new commits are in master now in the changelog). I created that branch mostly as a place to store a bit of release engineering work for later, I do not think the specific history of that branch is relevent and needs to be merged rather than rebased.

Furthermore, we should see if there are any other PRs ready to be merged (or important enough to be fixed and merged), but we should also probably be very conservative (i.e. not get caught up in fixing this and then ending up not releasing). I recall there were a few things I wanted to tackle, but frankly none of them is probably important enough to hold up the release.

One thing we should probably fix is #710, which I think prevents hamster from working at all on Python 3.11. I see there are (since just now) two PRs to fix this, but let's continue discussion about that in those PRs and the issue.

**Comment by DirkHoffmann** [comment]
Thanks for your feedback, @aquaherd. I think @matthijskooijman has already prepared the release with the release notes in the [release-3.0.3](https://github.com/projecthamster/hamster/tree/release-3.0.3) branch (missing probably the 5 last commits in master), and the effort for the release may be minimal
Se let's see, if he wants to pick this up in the coming days. Otherwise I will do my best to get the release out (and cleanly) in the next month.

**Comment by GeraldJansen** [comment]
> @GeraldJansen, I thought you had permissions to tag/release also. Am I wrong?

@DirkHoffmann I am just a random contributor, as already discussed here: https://github.com/projecthamster/hamster/issues/588#issuecomment-600185713.

**Comment by GeraldJansen** [comment]
Please consider inclusion of PR #699, a trivial fix for a cosmetically ugly bug.

**Comment by APCBoston** [comment]
Hey, I'm just catching up on this thread from the past couple of months but I use Hamster pretty routinely and would love to help out.  I'll take a look at the issues backlog but also would encourage folks that are more familiar with it to make use of the `help wanted` tag :-)

**Comment by kde-baskets-user** [comment]
I am using Hamster pretty much everyday last 7 or so years tracking my entire life. I am still yet to see any close competitor in this niche both either in GNOME or KDE desktops as well.  Apparent lack of maintaining is a very serious situation considering there is no easy switch to alternative even in a bigger linux landscape. 

I urge people possibly willing to contribute to go through an organizational step and set up sort of discussion to clarify who can do what and is there a  chance to revitalize the project. Thanks.

**Comment by salim-b** [comment]
For Gnome, there's [**Furtherance**](https://github.com/lakoliu/Furtherance). It's simple, maintained, and very resource-efficient (thanks to being written in Rust). It also has *working* Gnome idle detection.

**Comment by louisdoe** [comment]
Hello
any news on a potential further maintenance ? Still stuck with Ubuntu and 3.0.2 which needs fixes.
Thanks

**Comment by matthijskooijman** [comment]
I've done a bit more work on (reviewing) some existing PR's, I'll see if I can merge some of them today or tomorrow. I do not want to merge big things that cause further delays, but I've mostly focused on either small low hanging fruit, or stuff that improves the workflow (i.e. fixes in the flatpak build or pull request flow that make it easier to test PRs and publish a build).

One remaining thing is figuring out the release flow itself (looking at #608 there might be some translation-related work that needs to happen that we have not figured out yet), and maybe see if we can automate this a bit (ideally I would say a release would consist of filling the changelog/NEWS file and making a tag, and have a github workflow generate a source tarball with the version number added and a flatpak build and upload it as release artifacts automatically).

**Comment by rhertzog** [comment]
Yet another friendly ping because we really a new release... @matthijskooijman @DirkHoffmann 

I don't really understand that fear of release. Release early and often is a usual mantra and a git tag is more than enough to satisfy the need of distribution packagers like me. Not saying that it needs to be rushed, but also that you shouldn't worry of forgetting some things.... if you do people will report the issues and it will always be time to put out another bugfix release.

**Comment by DirkHoffmann** [comment]
AFAIAC, the fear is to release something, which I have not had time to test myself. But you seem to be very confident that nothing can go wrong, @rhertzog. So maybe we should the approach with trust. Next week-end + week is a good opportunity for me to respond to this long-standing request. 
Unfortunately we don't have a way to reorganise permissions as might fit, and although there is the possibility _in theory_ to fork the complete project, there are practical issues discussed above, which make such a fork unlikely to succeed.
So I agree that the handful of actors, who accepted the permissions on this repository a couple of years ago, should use them for the benefit of the community. Maybe we can distribute the tasks among us, @matthijskooijman, @rhertzog, @mwilck, after due splitting into small pieces and some coordination and exchange?

**Comment by mwilck** [comment]
Note that I am not in the hamster maintainers group. I'm working on the GNOME extension mostly.

In general, I think we shouldn't shy away from making releases. Will there be bugs? Most certainly. Then we'll fix them and create a new release.

I believe that currently most active users of hamster are running from the release-3.0.3 branch or from the master branch anyway, so we can't do much harm by creating a release.

**Comment by matthijskooijman** [comment]
> I don't really understand that fear of release. 

Speaking for myself, there is (I think) no fear, just lack of time to make the last couple of steps of figuring out the proper release process, with a little bit more documentation and automation.

Motivated by recent activity, I've spent some time the last few days figuring out how to handle version numbers better, and (after some sidetracks about mismatching application ids that I've investigated but am going to ignore until after a release) I think I have a plan (basically as discussed in #608 already) that I'll try to implement in the coming days.

I think one other potentially relevant bit before release is to look at translations: Is there anything that needs to be done (manually) at release time wrt translations? Are there any updated strings or translations or whatnot that need some tooling to be run? I haven't looked at this at all, but [this card](https://github.com/projecthamster/hamster/projects/1#card-27399663) suggests that there is something translation-related to be done (but also [this comment](https://github.com/projecthamster/hamster/issues/588#issuecomment-600225334) that suggests that the translation stuff is not up-to-date). @DirkHoffmann is that something you might have a look at? Or maybe @mwilck, it seems you have previously (long time ago) submitted #559 which also relates to i18n work (haven't looked at it at all yet, though)?

**Comment by mwilck** [comment]
> Or maybe @mwilck, it seems you have previously (long time ago) submitted https://github.com/projecthamster/hamster/pull/559

Indeed, a long time ago. I hardly remember ;-)

And as I said back then, it was a "rough ride". I recall that hamster's i18n code is very old and lots of it has been deprecated / replaced by different tools in the meantime. Isn't waf itself deprecated these days? My work back then was a lot of trial-and-error. I would say it can be used as groundwork for an i18n overhaul of hamster, but not more. I wouldn't recommend to do an i18n overhaul, or anything i18n related indeed, before a 3.0.3 release.

The translations are not optimal? No, they aren't. But if we wait until everything is polished, it will take another year or more until the release is out. In the meantime, people will be running hamster from git. Which is fine too of course, but then we should just announce that we don't do any releases any more.

Noone in the current team has lots of free resources to put into hamster. Therefore we should also make low-effort releases. hamster has traditionally put more effort into releases than most other projects I'm involved in. More often than not, projects just create a tag. I'm not saying that's good, but perhaps there's a middle ground between that and the complex procedure that hamster has been using in the past.

**Comment by matthijskooijman** [comment]
>  I wouldn't recommend to do an i18n overhaul, or anything i18n related indeed, before a 3.0.3 release.

I definitely agree that we should not do any overhaul or improvements before release. My question is mostly: Is there anything that needs to happen at release time wrt translations (i.e. something to update the translation files for changes in the code, or changes in translations to make them take effect). The answer is likely no, but I haven't looked at all, so I hope someone has :-)

So, looking at what I think needs doing before release:
 - [ ] Update waf, to allow running on modern python versions, this is nearly finished in #421 
 - [ ] Make versioning in the code a bit more correct and simple (i.e. implement option 1 from https://github.com/projecthamster/hamster/issues/608#issuecomment-1530024870). I plan to do this next.
 - [ ] Add a version number to flatpak builds (this involves renaming the metainfo.xml file - I think I know how to approach this, ignoring all other application id issues from #725 and will prepare a PR next).
 - [ ] Create release notes / NEWS file, a start was made in #609, which needs to be updated using recently made git commits
 - [ ] Verify if anything i18n-related needs to be done to release (probably not).

Then, steps for the actual release:
 1. Update #609 with the complete NEWS.md file
 2. Make a commit that sets the version number (maybe same commit that finalizes the NEWS file, or just the NEWS file header)
 3. Tag that commit
 4. Create a github release with the notes from the NEWS file, and attach the flatpak build (maybe also a source tarball? It would be just a git export, but I think having an actual tarball with a predictable checksum would be useful for the Debian package maybe, @rhertzog? Or is just exporting from git also fine)?
 5. Create a new commit that removes the version number again and adds a `## Unreleased changes` or so header to `NEWS.md` to collect changes already before release.

Ideally, steps 4 and 5 would be automated using github actions (I already have most of step 4 [implemented elsewhere](https://github.com/3devo/PCB-workflows/blob/dev/.github/workflows/dispatcher.yml)).

I also think it would be good to update/restructure the README a bit more to make it easier for people tot start using hamster (i.e. solve #660, but that would be fine after tagging a release (since then we also have our first versioned flatpak build available for the README to refer to).

**Comment by matthijskooijman** [comment]
I've had a look at the translations, and it seems that even though a lot of them are outdated (including the .pot files that collect translateable strings from the sources), the translated strings that are still present and applicable do work as expected (tested in the flatpak build). So I think there is some work to get the process of updating the translations running again, but there does not seem to be anything needed to get a release out with what we have now.

I've created #741 for discussion on further improvements.

**Comment by DirkHoffmann** [comment]
Let's also update this ticket by announcing that we try to release 3.0.3 by today. I think we are almost there and took into account the most urgent requests mentioned above. Maybe someone else wants to check or give feedback on short notice?

**Comment by matthijskooijman** [comment]
It's taken way longer than it should have, but we've released 3.0.3!

Next up is updating documentation to match, and I'll try to start some discussion on plans for the next release in the coming week.

**Comment by rhertzog** [comment]
> Create a github release with the notes from the NEWS file, and attach the flatpak build (maybe also a source tarball? It would be just a git export, but I think having an actual tarball with a predictable checksum would be useful for the Debian package maybe, @rhertzog? Or is just exporting from git also fine)?

The automated "git archive" export provided by Github is sufficient, there's no need to generate and store a tarball. We have tools in Debian to rebuild a bit-for-bit identical tarball from the content that we have in Git and some extra data. FTR, the pristine-tar tool provides this feature.
